[package]
authors = ["Matthias Drescher <matthias_p_drescher@t-online.de>"]
name = "cppvortrag"
version = "0.1.0"

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
rand = "*"
rayon = "0.8.2"
tokio-timer = "0.1"

[lib]
name = "testdata"
path = "src/testdata.rs"
